# Generated by Django 2.1.5 on 2019-04-02 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofreg', models.DateField()),
                ('branch_id', models.CharField(default='', max_length=100)),
                ('b_name', models.CharField(max_length=100)),
                ('b_add', models.CharField(default='', max_length=200)),
                ('b_loc', models.CharField(max_length=200)),
                ('b_phone', models.BigIntegerField()),
                ('email', models.CharField(default='', max_length=30)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='employ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofjoin', models.DateField()),
                ('timeofjoin', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(default='', max_length=100)),
                ('add', models.CharField(max_length=200)),
                ('town', models.CharField(default='', max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phn', models.BigIntegerField()),
                ('out', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=30)),
                ('password', models.CharField(max_length=200)),
                ('usertype', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ', models.CharField(max_length=100)),
                ('p_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(default='nil', max_length=100)),
                ('manfac', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('branch', models.CharField(default='', max_length=100)),
                ('pname', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('brand', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=100)),
                ('qua', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='stk',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.stock'),
        ),
        migrations.AddField(
            model_name='branch',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Login'),
        ),
    ]
